<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)build\intermediate\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)build\intermediate\bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
</Project>
