<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>false</UseWPF>
    <AssemblyName>QuickDock</AssemblyName>
    <RootNamespace>QuickDock</RootNamespace>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <Version>1.1.0</Version>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0</InformationalVersion>
    <Product>QuickDock</Product>
    <Authors>maktak-105</Authors>
    <Copyright>Copyright (c) 2026 maktak-105</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>QuickDock.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\QuickDock-icon.png" LogicalName="QuickDock.icon.png" />
  </ItemGroup>
</Project>
